steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/next-career-backend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/next-career-backend:latest'
      - '-f'
      - 'backend/Dockerfile'
      - './backend'
    
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/next-career-backend'
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'next-career-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/next-career-backend:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/next-career-backend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/next-career-backend:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
