#!/bin/bash

# Supabase + SendGrid Setup Complete!
# ====================================

echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║  ✅ SUPABASE + SENDGRID SETUP - DEPENDENCIES INSTALLED                     ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""

echo "🎉 All Python dependencies installed successfully!"
echo ""
echo "✅ Installed packages:"
echo "   • FastAPI & Uvicorn - Backend framework"
echo "   • Supabase - PostgreSQL database & auth"
echo "   • SendGrid - Email delivery service"
echo "   • Firebase Admin - Authentication & cloud functions"
echo "   • Stripe - Payment processing"
echo "   • Google Gemini AI - AI analysis"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "📋 NEXT STEPS TO GET RUNNING"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""

echo "📌 STEP 1: Run Database Migrations in Supabase"
echo "   ───────────────────────────────────────────"
echo "   1. Go to: https://supabase.com/dashboard"
echo "   2. Select your project: 'Next Career Intelligence'"
echo "   3. Go to: SQL Editor (left sidebar)"
echo "   4. Create a new query"
echo "   5. Copy ALL content from:"
echo "      backend/migrations/001_create_users_table.sql"
echo "   6. Click 'Run' to execute"
echo "   7. Repeat steps 4-6 for:"
echo "      • backend/migrations/002_create_verification_codes_table.sql"
echo "      • backend/migrations/003_create_password_resets_table.sql"
echo "      • backend/migrations/004_create_onboarding_table.sql"
echo ""

echo "📌 STEP 2: Add SendGrid API Key"
echo "   ──────────────────────────────"
echo "   1. Go to: https://app.sendgrid.com"
echo "   2. Click: Settings → API Keys"
echo "   3. Click: 'Create New Static Key'"
echo "   4. Name it: 'NEXT Career Intelligence - Dev' (or any name)"
echo "   5. Copy the API key (starts with 'SG.')"
echo "   6. Open: backend/.env"
echo "   7. Replace: SENDGRID_API_KEY=SG.your-sendgrid-api-key-here"
echo "              with the key you copied"
echo "   8. Save the file"
echo ""

echo "📌 STEP 3: Start the Backend Server"
echo "   ──────────────────────────────────"
echo "   Terminal 1:"
echo "   $ cd backend"
echo "   $ source venv/bin/activate"
echo "   $ python -m uvicorn app.main:app --reload"
echo ""
echo "   Expected output:"
echo "   Uvicorn running on http://127.0.0.1:8000"
echo ""

echo "📌 STEP 4: Start the Frontend Development Server"
echo "   ──────────────────────────────────────────────"
echo "   Terminal 2:"
echo "   $ cd frontend"
echo "   $ npm run dev"
echo ""
echo "   Expected output:"
echo "   ▲ Next.js 15.x.x"
echo "   - Local: http://localhost:3000"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "🧪 TESTING THE SETUP"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""

echo "Test 1: Backend Health Check"
echo "   $ curl http://localhost:8000/api/health"
echo "   Expected: {\"status\": \"healthy\"}"
echo ""

echo "Test 2: Frontend Loads"
echo "   Visit: http://localhost:3000"
echo "   Expected: NEXT Career Intelligence homepage"
echo ""

echo "Test 3: Sign Up Flow"
echo "   1. Go to http://localhost:3000/signup"
echo "   2. Enter email and password"
echo "   3. Check email for verification code"
echo "   4. Paste verification code (should come from SendGrid)"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "📁 PROJECT STRUCTURE"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "backend/"
echo "  ├── venv/                           # Python virtual environment (just created)"
echo "  ├── app/"
echo "  │   ├── main.py                     # FastAPI app entry point"
echo "  │   ├── api/"
echo "  │   │   ├── auth.py                 # Authentication endpoints"
echo "  │   │   ├── onboarding.py           # Onboarding endpoints"
echo "  │   │   ├── analyze.py              # AI analysis endpoints"
echo "  │   │   ├── jobs.py                 # Job search endpoints"
echo "  │   │   └── health.py               # Health check endpoint"
echo "  │   ├── services/"
echo "  │   │   ├── supabase_client.py      # Database operations"
echo "  │   │   ├── email_service.py        # SendGrid email delivery"
echo "  │   │   ├── ai_analyzer.py          # Gemini AI integration"
echo "  │   │   ├── coursera_service.py     # Coursera API integration"
echo "  │   │   └── onet_service.py         # O*NET API integration"
echo "  │   ├── models/"
echo "  │   │   ├── database.py             # SQLAlchemy models"
echo "  │   │   └── schemas.py              # Pydantic schemas"
echo "  │   ├── core/"
echo "  │   │   └── config.py               # Configuration settings"
echo "  │   └── db/"
echo "  │       └── database.py             # Database initialization"
echo "  ├── migrations/                     # Database migration scripts (just created)"
echo "  │   ├── 001_create_users_table.sql"
echo "  │   ├── 002_create_verification_codes_table.sql"
echo "  │   ├── 003_create_password_resets_table.sql"
echo "  │   └── 004_create_onboarding_table.sql"
echo "  ├── requirements.txt                # Python dependencies"
echo "  ├── .env                            # Environment configuration (fill in SendGrid key)"
echo "  └── pyproject.toml                  # Project metadata"
echo ""
echo "frontend/"
echo "  ├── src/"
echo "  │   ├── app/"
echo "  │   │   ├── layout.tsx              # Root layout"
echo "  │   │   └── page.tsx                # Homepage"
echo "  │   ├── components/                 # React components"
echo "  │   └── lib/"
echo "  │       ├── supabase.ts             # Supabase client"
echo "  │       ├── firebase.ts             # Firebase config"
echo "  │       ├── api.ts                  # API client"
echo "  │       └── types.ts                # TypeScript types"
echo "  ├── .env.local                      # Frontend environment (already configured)"
echo "  ├── package.json                    # Node dependencies"
echo "  ├── next.config.mjs                 # Next.js config"
echo "  └── tsconfig.json                   # TypeScript config"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "🔐 ENVIRONMENT VARIABLES CHECKLIST"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "backend/.env"
echo "  ✅ SUPABASE_URL=https://whxbxjpymksgvixudnjh.supabase.co"
echo "  ✅ SUPABASE_SERVICE_KEY=[Present - Admin access]"
echo "  ✅ SUPABASE_ANON_KEY=[Present - Public access]"
echo "  ✅ DATABASE_URL=postgresql://[Present]"
echo "  ✅ GEMINI_API_KEY=[Present]"
echo "  ✅ STRIPE_SECRET_KEY=[Present]"
echo "  ⏳ SENDGRID_API_KEY=SG.your-sendgrid-api-key-here [← FILL THIS IN]"
echo "  ✅ SENDGRID_FROM_EMAIL=noreply@nextcareer.ai"
echo "  ✅ SENDGRID_FROM_NAME=NEXT Career Intelligence"
echo "  ✅ APP_URL=http://localhost:3000"
echo "  ✅ API_URL=http://localhost:8000"
echo ""
echo "frontend/.env.local"
echo "  ✅ NEXT_PUBLIC_API_URL=http://localhost:8000"
echo "  ✅ NEXT_PUBLIC_SUPABASE_URL=[Present]"
echo "  ✅ NEXT_PUBLIC_SUPABASE_ANON_KEY=[Present]"
echo "  ✅ NEXT_PUBLIC_GOOGLE_CLIENT_ID=[Present]"
echo "  ✅ NEXT_PUBLIC_FIREBASE_API_KEY=[Present]"
echo "  ✅ All other configs present"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "💡 TROUBLESHOOTING"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "Issue: 'Connection refused' when accessing backend"
echo "Fix:   Make sure backend server is running (Terminal 1)"
echo "       Check: http://localhost:8000/api/health"
echo ""
echo "Issue: Database error when signing up"
echo "Fix:   Make sure all 4 migrations were run in Supabase SQL Editor"
echo "       Re-run them one by one"
echo ""
echo "Issue: Email not being sent"
echo "Fix:   1. Verify SENDGRID_API_KEY is set in backend/.env"
echo "       2. Verify it's the correct key from https://app.sendgrid.com"
echo "       3. Check backend logs for SendGrid errors"
echo "       4. Verify SENDGRID_FROM_EMAIL is verified in SendGrid dashboard"
echo ""
echo "Issue: 'Module not found' Python errors"
echo "Fix:   Make sure you're in the virtual environment:"
echo "       $ source backend/venv/bin/activate"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "📚 DOCUMENTATION"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "Available guides in project root:"
echo "  • SUPABASE_SENDGRID_SETUP.md     - Database & email setup guide"
echo "  • FRONTEND_SUPABASE_SETUP.md     - Frontend integration details"
echo "  • SENDGRID_DNS_SETUP.md          - Email domain configuration"
echo "  • QUICK_START_SETUP.md           - Quick reference card"
echo "  • API_TESTING.md                 - API endpoint testing guide"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "✨ YOU'RE ALL SET!"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "Next action: Fill in the SendGrid API key in backend/.env, then follow STEP 3"
echo ""
